#!/usr/bin/env python3
# unit_test/spirent/unit_test_stc_bgp_device.py
our_version = 102
'''
****************************
unit_test_stc_bgp_device.py
****************************

Description
-----------
Generates Ansible playbook conformant with Spirent Ansible module: stc
This playbook creates a BGP device under an existing emulated device

Prerequisites
-------------

    1.  To run the playbook generated by this script,
        Spirent's Ansible libraries, and their prerequisites,
        must be installed.

        https://github.com/Spirent/stc-ansible

    2.  Playbooks created with the following ScriptKit classes
        (or equivilent playbooks) must be run prior to running
        the playbook created with this script.

======================  ====================  ===============================
Class                   File                  Example script
======================  ====================  ===============================
StcSession()            stc_session.py        unit_test_stc_session.py
StcPorts()              stc_ports.py          unit_test_stc_ports.py
StcPortControl()        stc_port_control.py   unit_test_stc_port_control.py
StcDevice()             stc_device.py         unit_test_stc_device.py
StcDeviceConfigIpv4()   stc_device_config.py  unit_test_stc_device_config.py
StcDeviceConfigIpv6()   stc_device_config.py  unit_test_stc_device_config.py
======================  ====================  ===============================

'''
from ask.common.playbook import Playbook
from ask.common.log import Log
from ask.spirent.stc_bgp_device import StcBgpDevice

ansible_module = 'stc_bgp_device'
ansible_host = 'labserver-2001'
log = Log('unit_test_{}'.format(ansible_module), 'INFO', 'DEBUG')

def playbook():
    pb = Playbook(log)
    pb.profile_spirent()
    pb.file = '/tmp/{}.yaml'.format(ansible_module)
    pb.name = 'unit_test_{}'.format(ansible_module)
    pb.add_host(ansible_host)
    return pb

def add_task_name(task):
    task.append_to_task_name('{} v{}, {}'.format(ansible_module, our_version, ansible_host))
    for key in sorted(task.scriptkit_properties):
        task.append_to_task_name(key)

def add_task(pb):
    task = StcBgpDevice(log)
    task.action = 'create'
    task.count = 1
    task.under = 'device_1'
    task.asn = 12000
    task.dut_asn = 12000
    task.ip_version = 'IPV4'
    task.name = 'bgp_device_1'
    add_task_name(task)
    task.update()
    pb.add_task(task)

pb = playbook()
add_task(pb)
pb.append_playbook()
pb.write_playbook()
log.info('wrote {}'.format(pb.file))
