#!/usr/bin/env python3
# unit_test/spirent/unit_test_stc_device.py
our_version = 102
'''
******************************
unit_test_stc_device.py
******************************

Description
-----------
Generates Ansible playbook conformant with Spirent Ansible module: stc
This playbook creates a Spirent mac, ipv4, and ipv6 Spirent emulated
devices.

Prerequisites
-------------

    1.  To run the playbook generated by this script,
        Spirent's Ansible libraries, and their prerequisites,
        must be installed.

        https://github.com/Spirent/stc-ansible

    2.  Playbooks created with the following ScriptKit classes
        (or equivilent playbooks) must be run prior to running
        the playbook created with this script.

======================  ====================  ===============================
Class                   File                  Example script
======================  ====================  ===============================
StcSession()            stc_session.py        unit_test_stc_session.py
StcPorts()              stc_ports.py          unit_test_stc_ports.py
StcPortControl()        stc_port_control.py   unit_test_stc_port_control.py
======================  ====================  ===============================

'''
from ask.common.playbook import Playbook
from ask.common.log import Log
from ask.spirent.stc_device import StcDeviceMac, StcDeviceIpv4, StcDeviceIpv6

ansible_module = 'stc_device'
ansible_host = 'labserver-2001'
log = Log('unit_test_{}'.format(ansible_module), 'INFO', 'DEBUG')

def playbook():
    pb = Playbook(log)
    pb.profile_spirent()
    pb.file = '/tmp/{}.yaml'.format(ansible_module)
    pb.name = 'unit_test_{}'.format(ansible_module)
    pb.add_host(ansible_host)
    return pb

def add_task_name(task):
    task.append_to_task_name('{} v{}, {}'.format(ansible_module, our_version, ansible_host))
    for key in sorted(task.scriptkit_properties):
        task.append_to_task_name(key)

def add_task_stc_device_mac(pb):
    task = StcDeviceMac(log)
    task.create_count = 1
    task.device_count = 20
    task.device_name = 'mac_device_1'
    task.port_name = '401_mac_port'
    add_task_name(task)
    task.update()
    pb.add_task(task)

def add_task_stc_device_ipv4(pb):
    task = StcDeviceIpv4(log)
    task.create_count = 1
    task.device_count = 20
    task.device_name = 'ipv4_device_1'
    task.port_name = '402_ipv4_port'
    add_task_name(task)
    task.update()
    pb.add_task(task)

def add_task_stc_device_ipv6(pb):
    task = StcDeviceIpv6(log)
    task.create_count = 2
    task.device_count = 10
    task.device_name = 'ipv6_device_1'
    task.port_name = '403_ipv6_port'
    add_task_name(task)
    task.update()
    pb.add_task(task)

pb = playbook()
add_task_stc_device_mac(pb)
add_task_stc_device_ipv4(pb)
add_task_stc_device_ipv6(pb)
pb.append_playbook()
pb.write_playbook()
log.info('wrote {}'.format(pb.file))
