#!/usr/bin/env python3
# unit_test/spirent/unit_test_stc_session.py
our_version = 102
'''
****************************
unit_test_stc_session.py
****************************

Description
-----------
Generates Ansible playbook conformant with Spirent Ansible module: stc

This playbook creates a session to a Spirent LabServer.

Prerequisites
-------------

    1.  To run the playbook generated by this script,
        Spirent's Ansible libraries, and their prerequisites,
        must be installed.

        https://github.com/Spirent/stc-ansible

'''
from ask.common.playbook import Playbook
from ask.common.log import Log
from ask.spirent.stc_session import StcSession

ansible_module = 'stc_session'
ansible_host = 'labserver-2001'
log = Log('unit_test_{}'.format(ansible_module), 'INFO', 'DEBUG')

def playbook():
    pb = Playbook(log)
    pb.profile_spirent()
    pb.file = '/tmp/{}.yaml'.format(ansible_module)
    pb.name = 'unit_test_{}'.format(ansible_module)
    pb.add_host(ansible_host)
    return pb

def add_task_name(task):
    task.append_to_task_name('{} v{}, {}'.format(ansible_module, our_version, ansible_host))
    for key in task.scriptkit_properties:
        task.append_to_task_name(key)

def add_task_stc_session_create(pb):
    task = StcSession(log)
    task.command = 'create' # optional. create is the default
    task.name = 'east_west'
    task.user = 'Administrator'
    task.password = 'spirent'
    add_task_name(task)
    task.update()
    pb.add_task(task)

def add_task_stc_session_delete(pb):
    '''
    delete is currently not supported.  When support
    is added, this is what it will look like.
    '''
    task = StcSession(log)
    task.command = 'delete'
    task.name = 'east_west'
    task.user = 'Administrator'
    add_task_name(task)
    task.update()
    pb.add_task(task)

pb = playbook()
add_task_stc_session_create(pb)
#add_task_stc_session_delete(pb)
pb.append_playbook()
pb.write_playbook()
log.info('wrote {}'.format(pb.file))
