#!/usr/bin/env python3
# unit_test/spirent/unit_test_stc_ports.py
our_version = 102
'''
****************************
unit_test_stc_ports.py
****************************

Description
-----------
Generates Ansible playbook conformant with Spirent Ansible module: stc
This playbook creates three ports on module 1 and three ports on module 2
of chassis 1.

Prerequisites
-------------

    1.  To run the playbook generated by this script,
        Spirent's Ansible libraries, and their prerequisites,
        must be installed.

        https://github.com/Spirent/stc-ansible

    2.  Playbooks created with the following ScriptKit classes
        (or equivilent playbooks) must be run prior to running
        the playbook created with this script.

======================  ====================  ===============================
Class                   File                  Example script
======================  ====================  ===============================
StcSession()            stc_session.py        unit_test_stc_session.py
======================  ====================  ===============================

'''
from ask.common.playbook import Playbook
from ask.common.log import Log
from ask.spirent.stc_ports import StcPorts

ansible_module = 'stc_ports'
ansible_host = 'labserver-2001'
log = Log('unit_test_{}'.format(ansible_module), 'INFO', 'DEBUG')

def playbook():
    pb = Playbook(log)
    pb.profile_spirent()
    pb.file = '/tmp/{}.yaml'.format(ansible_module)
    pb.name = 'unit_test_{}'.format(ansible_module)
    pb.add_host(ansible_host)
    return pb

def add_task_name(task):
    task.append_to_task_name('{} v{}, {}'.format(ansible_module, our_version, ansible_host))
    for key in task.scriptkit_properties:
        task.append_to_task_name(key)

def add_stc_port(task, chassis, module, port):
    task.chassis = chassis
    task.module = module
    task.port = port
    # This sets the name of the task, not the name of the port.
    add_task_name(task)
    # task.name is the name of the port, not the name of the task.
    # By default, task.name will be the following format.
    #task.name = 'Stc{}/{}/{}'.format(chassis, module, port)
    task.add_port()

pb = playbook()
task = StcPorts(log)

task.action = 'create' # create, delete

chassis = 1
module = 1
for port in [1,5]:
    add_stc_port(task, chassis, module, port)

task.update()
pb.add_task(task)
pb.append_playbook()
pb.write_playbook()
log.info('wrote playbook {}'.format(pb.file))
