${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_aaa_server.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_aaa_server_host.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_acl_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_acls.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_banner.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bfd_global.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bfd_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bgp.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bgp_af.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bgp_global.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bgp_neighbor.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bgp_neighbor_address_family.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_bgp_neighbor_af.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_command.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_config.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_evpn_global.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_evpn_vni.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_feature.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_hsrp.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_hsrp_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_igmp.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_igmp_snooping.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_interface.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_interface_ospf.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_l2_interface.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_l2_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_l3_interface.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_l3_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_lacp_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_lag_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_lldp_global.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_lldp_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_logging.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_ntp.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_ntp_auth.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_ntp_options.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_nxapi.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_ospf.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_ospf_interfaces.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_ospfv2.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_overlay_global.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_pim.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_pim_interface.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_pim_rp_address.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_reboot.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_snmp_community.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_snmp_contact.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_snmp_host.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_snmp_location.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_static_routes.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_system.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vlan.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vlans.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vpc.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vpc_interface.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vrf.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vrf_interface.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vxlan_vtep.py
${HOME}/repos/ask/unit_test/cisco/nxos/unit_test_nxos_vxlan_vtep_vni.py